select * from dbo.AspNetUsers
select * from dbo.AspNetUserRoles
select * from dbo.AspNetRoles
select * from dbo.ShoppingCarts
select * from dbo.Companies
select * from dbo.Categories
select * from dbo.Products
select * from dbo.CoverType
select * from dbo.OrderHeaders
